stages:
  - static_analysis
  - test
  - build
  - deploy
  - security

cache:
  key: "$CI_REPOSITORY_URL"

before_script:
  - export GRADLE_USER_HOME="/cache/.gradle"
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US.UTF-8
  - export LC_ALL=en_US.UTF-8

"static_analysis:lint_debug":
  stage: static_analysis
  only:
    - refs
    - branches
    - merge_requests
    - tags
  image:
    name: gitlab.polidea.com:4567/runners/android:jdk11
  tags:
    - android_asimov
  script:
    - bundle check || bundle install --path=/cache
    - bundle exec fastlane lint_debug

"static_analysis:detekt":
  stage: static_analysis
  only:
    - refs
    - branches
    - merge_requests
    - tags
  image:
    name: gitlab.polidea.com:4567/runners/android:jdk11
  tags:
    - android_asimov
  script:
    - bundle check || bundle install --path=/cache
    - bundle exec fastlane detekt

"build:debug":
  stage: build
  only:
    - refs
    - branches
    - merge_requests
  image:
    name: gitlab.polidea.com:4567/runners/android:jdk11
  tags:
    - android_asimov
  script:
    - bundle check || bundle install --path=/cache
    - bundle exec fastlane build_debug

"testUnit:debug":
  stage: test
  only:
    - refs
    - branches
    - merge_requests
    - tags
  image:
    name: gitlab.polidea.com:4567/runners/android:jdk11
  tags:
    - android_asimov
  script:
    - bundle check || bundle install --path=/cache
    - bundle exec fastlane unit_tests_debug
  artifacts:
    expire_in: 1 day
    paths:
      - app/build/test-results/testDebugUnitTest/TEST-*.xml
      - app/build/reports/tests/testDebugUnitTest/
    reports:
      junit: app/build/test-results/testDebugUnitTest/TEST-*.xml

"testUI:debug":
  services:
    - name: gitlab.polidea.com:4567/runners/android-emulator:jdk11
      alias: android-emulator
      entrypoint: [ "/start-emulator.sh", "android-30", "x86", "pixel_xl" ]
  stage: test
  image:
    name: gitlab.polidea.com:4567/runners/android:jdk11
  tags:
    - android_asimov
  before_script:
    # Wait for the emulator to start
    - adb connect android-emulator:5555
    - adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
  script:
    - bundle check || bundle install --path=/cache
    - bundle exec fastlane ui_tests_debug
  only:
    - merge_requests
    - tags
  artifacts:
    expire_in: 1 day
    paths:
      - app/build/outputs/androidTest-results/connected/TEST-*.xml
      - app/build/reports/androidTests/connected/
    reports:
      junit: app/build/outputs/androidTest-results/connected/TEST-*.xml

"deploy:debug":
  stage: deploy
  image:
    name: gitlab.polidea.com:4567/runners/android:jdk11
  tags:
    - android_asimov
  only:
    - tags
  script:
    - bundle check || bundle install --path=/cache
    - bundle exec fastlane deploy_debug

"security:owasp_dependency_check":
  stage: security
  image:
    name: gitlab.polidea.com:4567/runners/android:jdk11
  tags:
    - android_asimov
  script:
    - bundle check || bundle install --path=/cache
    - bundle exec fastlane owasp_dependency_check
  artifacts:
    expire_in: 1 day
    paths:
      - app/build/reports/dependency-check-junit.xml
      - app/build/reports/dependency-check-report.html
    reports:
      junit: app/build/reports/dependency-check-junit.xml
  only:
    refs:
      - merge_requests
    changes:
      - build.gradle
      - app/build.gradle

"security:owasp_dependency_check_tag":
  stage: security
  image:
    name: gitlab.polidea.com:4567/runners/android:jdk11
  tags:
    - android_asimov
  only:
    - tags
  script:
    - bundle check || bundle install --path=/cache
    - bundle exec fastlane owasp_dependency_check
  artifacts:
    expire_in: 1 day
    paths:
      - app/build/reports/dependency-check-junit.xml
      - app/build/reports/dependency-check-report.html
    reports:
      junit: app/build/reports/dependency-check-junit.xml
